### ISSUE TITLE
Possible "direct binding" between ViewModel object and View?

### ISSUE THREAD

**Issue by Devepre** [quickbirdstudios/SwiftUI-Architectures#2]
I'm referring to the **ViewState MVVM** architecture from now.

I'm wondering how to use direct binding between ViewModel and View.

For example `NavigationLink` is accepting `isActive` parameter of type `Binding<Bool>`. I want to control this value through ViewModel instead of `View's @State` property. That is because only after ViewModel has finished with Input Trigger action, this binding value of ViewModel will be set to `true` what will cause `NavigationLink` to proceed.

Another example: how to move `@State  private var newMessage = ""` from the `View` to `ChatDetailState/ChatDetailViewModel`? It will ensure that ViewModel will always have latest message value and could react accordingly. As a benefit, `.addMessage` trigger will not handle `message` value since it's already in ViewModel.

**Comment by pauljohanneskraft** [comment]
Hey @Devepre !

I was also wondering about this problem. Since in **ViewState MVVM** there should only be a read-only state available to the view and all state changes should be initiated by an input being triggered. Therefore, I would suggest the following extension to create bindings. To make this API even easier to use, you can create extensions using keypaths as well, just as an example.

```swift
extension AnyViewModel {
    func bind<Value>(_ value: @escaping (State) -> Value,
                     to input: @escaping (Value) -> Input?) -> Binding<Value> {

        Binding(get: { value(self.state) },
                set: { input($0).map { self.trigger($0) } })
    }
}
```

This would allow you to create bindings like the following for a text property of your state and an input for that property:

```swift
viewModel.bind({ $0.text }, to: { .text($0) })
```

In your viewModel, you can then change the state depending on that input - that may be a bit of an overhead, but it would ensure that the viewModel state is read-only. Another option would be to make the state read-write and then ensuring that you are only writing to the state, whenever it would seriously impact code overhead.

**Comment by Devepre** [comment]
Hi @pauljohanneskraft ,

Sounds reasonable, thanks a lot!

I've tried both approaches a little bit in practice. For now, second approach with read-write state and KeyPaths "everywhere" is more enjoyable to me, because of cleaner API and less boilerplate code. It will look like this code snippet:

`viewModel.bind(on: \.text)`

 Also it's critical to have read-only state, that's why I've used `private(set) var state` but `func forceUpdate(_ newState: State)` as `ViewModel` protocol requirement while `AnyViewModel's` implementation will assert failure.

**Comment by savage7** [comment]
@Devepre 
Could you be so kind to share how you realized this?
`viewModel.bind(on: \.text)
`

**Comment by Devepre** [comment]
@savage7 it was tricky task, since I've moved to another approach a long time ago and didn't have commits pushed to the server. Anyway I've managed to find my old implementation. If it makes sense, I can make pull request to the original repo, anyway you can take a look implementation in forked version here https://github.com/Devepre/SwiftUI-Architectures/tree/develop commit [c69e644e6dfac461e172adb1804723b50c4eba01](https://github.com/Devepre/SwiftUI-Architectures/commit/c69e644e6dfac461e172adb1804723b50c4eba01)
